# Generated by Django 5.1.1 on 2024-09-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_book',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
